// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Projects\goProjects\LTCalendar\internal\repository/repository_interface.go

// Package mock_repository is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dimalewshin98-glitch/LTCalendar/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddTest mocks base method.
func (m *MockRepositoryInterface) AddTest(ctx context.Context, userID int, req model.ApiAddTestReq, endTime string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTest", ctx, userID, req, endTime)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTest indicates an expected call of AddTest.
func (mr *MockRepositoryInterfaceMockRecorder) AddTest(ctx, userID, req, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTest", reflect.TypeOf((*MockRepositoryInterface)(nil).AddTest), ctx, userID, req, endTime)
}

// GetTest mocks base method.
func (m *MockRepositoryInterface) GetTest(ctx context.Context, userID int, testUUID string) (model.ApiGetTestRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, userID, testUUID)
	ret0, _ := ret[0].(model.ApiGetTestRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest.
func (mr *MockRepositoryInterfaceMockRecorder) GetTest(ctx, userID, testUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTest), ctx, userID, testUUID)
}

// GetTests mocks base method.
func (m *MockRepositoryInterface) GetTests(ctx context.Context, userID int, excludeStarted bool) (model.ApiGetTestsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTests", ctx, userID, excludeStarted)
	ret0, _ := ret[0].(model.ApiGetTestsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTests indicates an expected call of GetTests.
func (mr *MockRepositoryInterfaceMockRecorder) GetTests(ctx, userID, excludeStarted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTests", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTests), ctx, userID, excludeStarted)
}

// GetUsersID mocks base method.
func (m *MockRepositoryInterface) GetUsersID(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersID", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersID indicates an expected call of GetUsersID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUsersID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUsersID), ctx)
}

// Login mocks base method.
func (m *MockRepositoryInterface) Login(ctx context.Context, req model.ApiLoginReq) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockRepositoryInterfaceMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockRepositoryInterface)(nil).Login), ctx, req)
}

// Ping mocks base method.
func (m *MockRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryInterfaceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepositoryInterface)(nil).Ping), ctx)
}

// Register mocks base method.
func (m *MockRepositoryInterface) Register(ctx context.Context, req model.ApiLoginReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockRepositoryInterfaceMockRecorder) Register(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRepositoryInterface)(nil).Register), ctx, req)
}

// SetDelete mocks base method.
func (m *MockRepositoryInterface) SetDelete(ctx context.Context, userID int, testUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDelete", ctx, userID, testUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDelete indicates an expected call of SetDelete.
func (mr *MockRepositoryInterfaceMockRecorder) SetDelete(ctx, userID, testUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDelete", reflect.TypeOf((*MockRepositoryInterface)(nil).SetDelete), ctx, userID, testUUID)
}

// SetTestStarted mocks base method.
func (m *MockRepositoryInterface) SetTestStarted(ctx context.Context, userID int, testUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTestStarted", ctx, userID, testUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTestStarted indicates an expected call of SetTestStarted.
func (mr *MockRepositoryInterfaceMockRecorder) SetTestStarted(ctx, userID, testUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTestStarted", reflect.TypeOf((*MockRepositoryInterface)(nil).SetTestStarted), ctx, userID, testUUID)
}

// UpdateTest mocks base method.
func (m *MockRepositoryInterface) UpdateTest(ctx context.Context, userID int, testUUID string, test model.ApiUpdateTestReq) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTest", ctx, userID, testUUID, test)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTest indicates an expected call of UpdateTest.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateTest(ctx, userID, testUUID, test interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTest", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateTest), ctx, userID, testUUID, test)
}
